apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{ .Values.service.name | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.service.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: default-secret
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3344
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.active }}
            - name: eureka.defaultZone
              value: {{ .Values.global.eurekaDefaultZone }}
            - name: rabbitmq.host
              value: {{ .Values.global.rabbitmq }}
            - name: rabbitmq.username
              value: {{ .Values.global.rabbitmqUsername }}
            - name: rabbitmq.password
              value: {{ .Values.global.rabbitmqPassword }}
            - name: mysql.host
              value: {{ .Values.global.mysqlHost }}
            - name: mysql.username
              value: "root"
            - name: mysql.password
              value: "1234"
            - name: giteeUser
              value: "zacharyy2023@outlook.com"
            - name: giteePassword
              value: "tomorrow0.0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
