apiVersion: v1
kind: Service
metadata:
  name: config-server-node
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 32440
      protocol: TCP
      name: config-server
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}
