apiVersion: v1
kind: Service
metadata:
  name: config-node
  labels:
    app: {{ .Values.service.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: eureka-node
  selector:
    app: {{ .Values.service.name }}
