annotations: #按名称输入的批注列表 （可选）.
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2 #chart API 版本
appVersion: 1.0.0 #包含的应用版本（可选）。不必遵守SemVer2规范，建议使用引号

description: eureka service #一句话对这个项目的描述（可选）
home: https://github.com/saashousekeeper/charts/tree/gh-pages/charts/eureka  #项目home页面的URL （可选）
keywords: #关于项目的一组关键字（可选）
  - eureka
  - http
  - https
  - web
  - java
  - register
maintainers: #（可选）
  - name: saashousekeeper #维护者名字（每个维护者都需要）
    url: https://github.com/saashousekeeper/charts #维护者URL（每个维护者可选）
name: eureka #chart名称 （必需）
sources: #项目源码的URL列表（可选）
  - https://httpd.apache.org
version: 1.0.0 #版本（必需），遵守SemVer2规范