apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: mysql
  repository: ""
  version: 1.0.0
- name: rabbitmq
  repository: ""
  version: 1.0.0
- name: config-server
  repository: ""
  version: 1.0.0
- name: eureka
  repository: ""
  version: 1.0.0
- name: frontend
  repository: ""
  version: 1.0.0
description: Helm Chart for Product Catalog Workshop
name: housekeeper
version: 1.0.0
