# Default values for housekeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
###
### INGRESS
###
ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
###
### housekeeper
###
housekeeper:
  api:
    skipEvents: true
    skipSecrets: false
    skipped: []