apiVersion: v1
kind: ConfigMap
binaryData: {}
metadata:
  annotations:
    description: ''
    originName: config
    currentVersion: '1'
  name: config
  namespace: default
  labels: {}
data:
  frontendAddress: ''
  SPRING_PROFILES_ACTIVE: {{ .Values.global.active }}
  CONFIG_SERVER: {{ .Values.global.configServer }}
  eureka.defaultZone: {{ .Values.global.eurekaDefaultZone }}
  mysql.host: {{ .Values.global.mysqlHost }}
  rabbitmq.host: {{ .Values.global.rabbitmqHost }}