kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-initdb-pv-volume1
  labels:
    type: local
    app: rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/rabbitmq/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-initdb-pvc-claim1
  labels:
    app: rabbitmq
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi