apiVersion: v1
kind: Service
metadata:
  name: {{ include "task.name" . }}
  labels:
    {{- include "task.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "task.name" . }}
  selector:
    {{- include "task.selectorLabels" . | nindent 4 }}
