apiVersion: v1
kind: Service
metadata:
  name: eureka-node
  labels:
    {{- include "eureka.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: eureka-node
  selector:
    {{- include "eureka.selectorLabels" . | nindent 4 }}
