{{ if .Values.nfs.mountOptions -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pv.name" . }}
  labels:
    mysql: {{ include "pv.name" . }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storageClass.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
  storageClassName: ""
  {{- if .Values.nfs.mountOptions }}
  mountOptions:
    {{- range .Values.nfs.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
{{ end -}}