{{- if .Values.mysql.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql.serviceAccountName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.mysql.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
