apiVersion: v1
kind: Service
metadata:
  name: mysql-node
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mysql-node
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
